//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Запись мат.
    /// </summary>
    // *** Start programmer edit section *** (ЗаписьМат CustomAttributes)

    // *** End programmer edit section *** (ЗаписьМат CustomAttributes)
    [AutoAltered()]
    [Caption("Запись мат")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаписьМатE", new string[] {
            "НомерЗаписи as \'Номер записи\'",
            "Материал as \'Материал\'",
            "ДатаСоздания as \'Дата создания\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Должность as \'Должность\'"}, Hidden=new string[] {
            "Сотрудники.Должность"})]
    [MasterViewDefineAttribute("ЗаписьМатE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Должность")]
    [View("ЗаписьМатL", new string[] {
            "НомерЗаписи as \'Номер записи\'",
            "Материал as \'Материал\'",
            "ДатаСоздания as \'Дата создания\'",
            "Сотрудники.Должность as \'Должность\'"})]
    public class ЗаписьМат : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЗаписи;
        
        private string fМатериал;
        
        private string fДатаСоздания;
        
        private IIS.KR.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ЗаписьМат CustomMembers)

        // *** End programmer edit section *** (ЗаписьМат CustomMembers)

        
        /// <summary>
        /// ДатаСоздания.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьМат.ДатаСоздания CustomAttributes)

        // *** End programmer edit section *** (ЗаписьМат.ДатаСоздания CustomAttributes)
        [StrLen(255)]
        public virtual string ДатаСоздания
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьМат.ДатаСоздания Get start)

                // *** End programmer edit section *** (ЗаписьМат.ДатаСоздания Get start)
                string result = this.fДатаСоздания;
                // *** Start programmer edit section *** (ЗаписьМат.ДатаСоздания Get end)

                // *** End programmer edit section *** (ЗаписьМат.ДатаСоздания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьМат.ДатаСоздания Set start)

                // *** End programmer edit section *** (ЗаписьМат.ДатаСоздания Set start)
                this.fДатаСоздания = value;
                // *** Start programmer edit section *** (ЗаписьМат.ДатаСоздания Set end)

                // *** End programmer edit section *** (ЗаписьМат.ДатаСоздания Set end)
            }
        }
        
        /// <summary>
        /// Материал.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьМат.Материал CustomAttributes)

        // *** End programmer edit section *** (ЗаписьМат.Материал CustomAttributes)
        [StrLen(255)]
        public virtual string Материал
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьМат.Материал Get start)

                // *** End programmer edit section *** (ЗаписьМат.Материал Get start)
                string result = this.fМатериал;
                // *** Start programmer edit section *** (ЗаписьМат.Материал Get end)

                // *** End programmer edit section *** (ЗаписьМат.Материал Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьМат.Материал Set start)

                // *** End programmer edit section *** (ЗаписьМат.Материал Set start)
                this.fМатериал = value;
                // *** Start programmer edit section *** (ЗаписьМат.Материал Set end)

                // *** End programmer edit section *** (ЗаписьМат.Материал Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаписи.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьМат.НомерЗаписи CustomAttributes)

        // *** End programmer edit section *** (ЗаписьМат.НомерЗаписи CustomAttributes)
        public virtual int НомерЗаписи
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьМат.НомерЗаписи Get start)

                // *** End programmer edit section *** (ЗаписьМат.НомерЗаписи Get start)
                int result = this.fНомерЗаписи;
                // *** Start programmer edit section *** (ЗаписьМат.НомерЗаписи Get end)

                // *** End programmer edit section *** (ЗаписьМат.НомерЗаписи Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьМат.НомерЗаписи Set start)

                // *** End programmer edit section *** (ЗаписьМат.НомерЗаписи Set start)
                this.fНомерЗаписи = value;
                // *** Start programmer edit section *** (ЗаписьМат.НомерЗаписи Set end)

                // *** End programmer edit section *** (ЗаписьМат.НомерЗаписи Set end)
            }
        }
        
        /// <summary>
        /// Запись мат.
        /// </summary>
        // *** Start programmer edit section *** (ЗаписьМат.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ЗаписьМат.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.KR.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ЗаписьМат.Сотрудники Get start)

                // *** End programmer edit section *** (ЗаписьМат.Сотрудники Get start)
                IIS.KR.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ЗаписьМат.Сотрудники Get end)

                // *** End programmer edit section *** (ЗаписьМат.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаписьМат.Сотрудники Set start)

                // *** End programmer edit section *** (ЗаписьМат.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ЗаписьМат.Сотрудники Set end)

                // *** End programmer edit section *** (ЗаписьМат.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаписьМатE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьМатE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьМатE", typeof(IIS.KR.ЗаписьМат));
                }
            }
            
            /// <summary>
            /// "ЗаписьМатL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаписьМатL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаписьМатL", typeof(IIS.KR.ЗаписьМат));
                }
            }
        }
    }
}
