//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Место хран.
    /// </summary>
    // *** Start programmer edit section *** (МестоХран CustomAttributes)

    // *** End programmer edit section *** (МестоХран CustomAttributes)
    [AutoAltered()]
    [Caption("Место хран")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МестоХранE", new string[] {
            "Расположение as \'Расположение\'",
            "ИмяМеста as \'Имя места\'",
            "ЗаписьМат as \'Запись мат\'",
            "ЗаписьМат.Материал as \'Материал\'"}, Hidden=new string[] {
            "ЗаписьМат.Материал"})]
    [MasterViewDefineAttribute("МестоХранE", "ЗаписьМат", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Материал")]
    [View("МестоХранL", new string[] {
            "Расположение as \'Расположение\'",
            "ИмяМеста as \'Имя места\'",
            "ЗаписьМат.Материал as \'Материал\'"})]
    public class МестоХран : ICSSoft.STORMNET.DataObject
    {
        
        private string fРасположение;
        
        private string fИмяМеста;
        
        private IIS.KR.ЗаписьМат fЗаписьМат;
        
        // *** Start programmer edit section *** (МестоХран CustomMembers)

        // *** End programmer edit section *** (МестоХран CustomMembers)

        
        /// <summary>
        /// ИмяМеста.
        /// </summary>
        // *** Start programmer edit section *** (МестоХран.ИмяМеста CustomAttributes)

        // *** End programmer edit section *** (МестоХран.ИмяМеста CustomAttributes)
        [StrLen(255)]
        public virtual string ИмяМеста
        {
            get
            {
                // *** Start programmer edit section *** (МестоХран.ИмяМеста Get start)

                // *** End programmer edit section *** (МестоХран.ИмяМеста Get start)
                string result = this.fИмяМеста;
                // *** Start programmer edit section *** (МестоХран.ИмяМеста Get end)

                // *** End programmer edit section *** (МестоХран.ИмяМеста Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МестоХран.ИмяМеста Set start)

                // *** End programmer edit section *** (МестоХран.ИмяМеста Set start)
                this.fИмяМеста = value;
                // *** Start programmer edit section *** (МестоХран.ИмяМеста Set end)

                // *** End programmer edit section *** (МестоХран.ИмяМеста Set end)
            }
        }
        
        /// <summary>
        /// Расположение.
        /// </summary>
        // *** Start programmer edit section *** (МестоХран.Расположение CustomAttributes)

        // *** End programmer edit section *** (МестоХран.Расположение CustomAttributes)
        [StrLen(255)]
        public virtual string Расположение
        {
            get
            {
                // *** Start programmer edit section *** (МестоХран.Расположение Get start)

                // *** End programmer edit section *** (МестоХран.Расположение Get start)
                string result = this.fРасположение;
                // *** Start programmer edit section *** (МестоХран.Расположение Get end)

                // *** End programmer edit section *** (МестоХран.Расположение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МестоХран.Расположение Set start)

                // *** End programmer edit section *** (МестоХран.Расположение Set start)
                this.fРасположение = value;
                // *** Start programmer edit section *** (МестоХран.Расположение Set end)

                // *** End programmer edit section *** (МестоХран.Расположение Set end)
            }
        }
        
        /// <summary>
        /// Место хран.
        /// </summary>
        // *** Start programmer edit section *** (МестоХран.ЗаписьМат CustomAttributes)

        // *** End programmer edit section *** (МестоХран.ЗаписьМат CustomAttributes)
        [PropertyStorage(new string[] {
                "ЗаписьМат"})]
        [NotNull()]
        public virtual IIS.KR.ЗаписьМат ЗаписьМат
        {
            get
            {
                // *** Start programmer edit section *** (МестоХран.ЗаписьМат Get start)

                // *** End programmer edit section *** (МестоХран.ЗаписьМат Get start)
                IIS.KR.ЗаписьМат result = this.fЗаписьМат;
                // *** Start programmer edit section *** (МестоХран.ЗаписьМат Get end)

                // *** End programmer edit section *** (МестоХран.ЗаписьМат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (МестоХран.ЗаписьМат Set start)

                // *** End programmer edit section *** (МестоХран.ЗаписьМат Set start)
                this.fЗаписьМат = value;
                // *** Start programmer edit section *** (МестоХран.ЗаписьМат Set end)

                // *** End programmer edit section *** (МестоХран.ЗаписьМат Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МестоХранE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МестоХранE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МестоХранE", typeof(IIS.KR.МестоХран));
                }
            }
            
            /// <summary>
            /// "МестоХранL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МестоХранL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МестоХранL", typeof(IIS.KR.МестоХран));
                }
            }
        }
    }
}
