//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Отпуск мат.
    /// </summary>
    // *** Start programmer edit section *** (ОтпускМат CustomAttributes)

    // *** End programmer edit section *** (ОтпускМат CustomAttributes)
    [AutoAltered()]
    [Caption("Отпуск мат")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ОтпускМатE", new string[] {
            "ДатаПроводки as \'Дата проводки\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.Должность as \'Должность\'"}, Hidden=new string[] {
            "Сотрудники.Должность"})]
    [MasterViewDefineAttribute("ОтпускМатE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Должность")]
    [View("ОтпускМатL", new string[] {
            "ДатаПроводки as \'Дата проводки\'",
            "Сотрудники.Должность as \'Должность\'"})]
    public class ОтпускМат : ICSSoft.STORMNET.DataObject
    {
        
        private string fДатаПроводки;
        
        private IIS.KR.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (ОтпускМат CustomMembers)

        // *** End programmer edit section *** (ОтпускМат CustomMembers)

        
        /// <summary>
        /// ДатаПроводки.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМат.ДатаПроводки CustomAttributes)

        // *** End programmer edit section *** (ОтпускМат.ДатаПроводки CustomAttributes)
        [StrLen(255)]
        public virtual string ДатаПроводки
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМат.ДатаПроводки Get start)

                // *** End programmer edit section *** (ОтпускМат.ДатаПроводки Get start)
                string result = this.fДатаПроводки;
                // *** Start programmer edit section *** (ОтпускМат.ДатаПроводки Get end)

                // *** End programmer edit section *** (ОтпускМат.ДатаПроводки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМат.ДатаПроводки Set start)

                // *** End programmer edit section *** (ОтпускМат.ДатаПроводки Set start)
                this.fДатаПроводки = value;
                // *** Start programmer edit section *** (ОтпускМат.ДатаПроводки Set end)

                // *** End programmer edit section *** (ОтпускМат.ДатаПроводки Set end)
            }
        }
        
        /// <summary>
        /// Отпуск мат.
        /// </summary>
        // *** Start programmer edit section *** (ОтпускМат.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ОтпускМат.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.KR.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ОтпускМат.Сотрудники Get start)

                // *** End programmer edit section *** (ОтпускМат.Сотрудники Get start)
                IIS.KR.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ОтпускМат.Сотрудники Get end)

                // *** End programmer edit section *** (ОтпускМат.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ОтпускМат.Сотрудники Set start)

                // *** End programmer edit section *** (ОтпускМат.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ОтпускМат.Сотрудники Set end)

                // *** End programmer edit section *** (ОтпускМат.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ОтпускМатE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтпускМатE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтпускМатE", typeof(IIS.KR.ОтпускМат));
                }
            }
            
            /// <summary>
            /// "ОтпускМатL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ОтпускМатL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ОтпускМатL", typeof(IIS.KR.ОтпускМат));
                }
            }
        }
    }
}
